// 29Items-Projects/1Java/2Healthcare Claims Processing/frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="app-container">
      <nav class="navbar">
        <div class="navbar-brand">
          <span class="brand-icon">+</span>
          Healthcare Claims Processing
        </div>
        <div class="navbar-menu">
          <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
          <a routerLink="/claims" routerLinkActive="active">Claims</a>
          <a routerLink="/review-queue" routerLinkActive="active">Review Queue</a>
          <a routerLink="/reports" routerLinkActive="active">Reports</a>
        </div>
        <div class="navbar-user">
          <span class="user-name">Test User</span>
          <button class="btn btn-secondary btn-sm">Logout</button>
        </div>
      </nav>

      <main class="main-content">
        <router-outlet></router-outlet>
      </main>

      <footer class="footer">
        <p>&copy; 2024 Healthcare Claims Processing. All rights reserved.</p>
      </footer>
    </div>
  `,
  styles: [`
    .app-container {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    .navbar {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 12px 24px;
      background: white;
      border-bottom: 1px solid var(--border-color);
      box-shadow: var(--shadow-sm);
    }

    .navbar-brand {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 18px;
      font-weight: 600;
      color: var(--primary-color);
    }

    .brand-icon {
      width: 32px;
      height: 32px;
      display: flex;
      align-items: center;
      justify-content: center;
      background: var(--primary-color);
      color: white;
      border-radius: 8px;
      font-size: 20px;
    }

    .navbar-menu {
      display: flex;
      gap: 8px;
    }

    .navbar-menu a {
      padding: 8px 16px;
      color: var(--text-secondary);
      text-decoration: none;
      border-radius: var(--border-radius);
      transition: all 0.2s ease;

      &:hover {
        background: var(--bg-secondary);
        color: var(--text-primary);
      }

      &.active {
        background: var(--primary-color);
        color: white;
      }
    }

    .navbar-user {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .user-name {
      color: var(--text-secondary);
    }

    .btn-sm {
      padding: 6px 12px;
      font-size: 13px;
    }

    .main-content {
      flex: 1;
      padding: 24px;
      max-width: 1400px;
      width: 100%;
      margin: 0 auto;
    }

    .footer {
      padding: 16px 24px;
      text-align: center;
      color: var(--text-muted);
      border-top: 1px solid var(--border-color);
      background: var(--bg-primary);
    }
  `]
})
export class AppComponent {
  title = 'Healthcare Claims Processing';
}

// 29Items-Projects/10Security/3-Web-App-Security-Scanner/frontend/src/App.vue
<script setup>
/**
 * App shell: top navigation + routed content. Navigation items are
 * role-aware (Targets / Users management are admin-only surfaces).
 */
import { useRouter } from 'vue-router'
import { authStore, isAdmin, logout } from './stores/auth.js'

const router = useRouter()

function onLogout() {
  logout()
  router.push({ name: 'login' })
}
</script>

<template>
  <div class="app-shell">
    <header class="app-header">
      <div class="app-title">
        <h1>🛡️ Web App Security Scanner</h1>
        <span class="app-sub">ZAP · SQLMap · XSS engine · ML severity</span>
      </div>

      <nav v-if="authStore.user" class="app-nav" aria-label="Main">
        <RouterLink :to="{ name: 'dashboard' }">Dashboard</RouterLink>
        <RouterLink v-if="isAdmin" :to="{ name: 'targets' }">Targets</RouterLink>
        <RouterLink v-if="isAdmin" :to="{ name: 'admin-users' }">Users</RouterLink>
      </nav>

      <div v-if="authStore.user" class="user-box">
        <span class="user-email" :title="authStore.user.email">{{ authStore.user.email }}</span>
        <span class="role-chip" :class="`role-${authStore.user.role}`">{{ authStore.user.role }}</span>
        <button class="logout" type="button" @click="onLogout">Log out</button>
      </div>
    </header>

    <main class="app-main">
      <RouterView />
    </main>
  </div>
</template>

<style>
:root {
  --bg: #0f1420;
  --panel: #1a2233;
  --border: #2a3550;
  --text: #e6ebf5;
  --muted: #8b96ad;
  --accent: #4f8cff;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
  background: var(--bg);
  color: var(--text);
}
.app-shell { max-width: 1100px; margin: 0 auto; padding: 0 16px 48px; }
.app-header {
  display: flex;
  align-items: center;
  gap: 16px;
  flex-wrap: wrap;
  padding: 20px 0 14px;
  border-bottom: 1px solid var(--border);
  margin-bottom: 20px;
}
.app-title h1 { font-size: 1.25rem; margin: 0; }
.app-sub { color: var(--muted); font-size: 0.8rem; }
.app-nav { display: flex; gap: 4px; flex-wrap: wrap; }
.app-nav a {
  color: var(--muted);
  text-decoration: none;
  padding: 6px 12px;
  border-radius: 6px;
  font-size: 0.92rem;
}
.app-nav a.router-link-active { color: var(--text); background: var(--panel); }
.user-box { display: flex; align-items: center; gap: 8px; margin-left: auto; }
.user-email {
  color: var(--muted);
  font-size: 0.85rem;
  max-width: 180px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.role-chip {
  font-size: 0.7rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 2px 8px;
  border-radius: 999px;
  background: var(--panel);
  border: 1px solid var(--border);
  color: var(--muted);
}
.role-chip.role-admin { color: #ff9d7a; border-color: #5e2f1e; }
.role-chip.role-scanner { color: #7ee2a8; border-color: #27503c; }
.logout {
  background: none;
  border: 1px solid var(--border);
  border-radius: 6px;
  color: var(--text);
  padding: 5px 12px;
  cursor: pointer;
  font-size: 0.85rem;
}
.logout:hover { border-color: var(--accent); }
.app-main { display: flex; flex-direction: column; gap: 20px; }
@media (max-width: 640px) {
  .user-box { margin-left: 0; width: 100%; justify-content: space-between; }
}
</style>
